#!/bin/sh

# This is a short-cut to execute tests on the parser.
# ./conf/torture_msgs{,2} contain various kind of messages.

#echo "=="
#echo "== Testing the parser contained in libosip."
#echo "== You can use the verbose mode (-v) to see the full message."
#echo "=="

ok=0
nok=0

i=0
while [ $i -lt 87 ]
do
set +x
#  mpatrol -C -S -L -j -d --list -p -t --use-debug ./test/torture_test $1 $i $2 $3
   ./torture_test ./res/sip$i 0 $1
   if [ "$?" -eq 0 ]; then
       echo "checking sip$i : passed";
       ok=`expr $ok + 1`;
   else
       echo "checking sip$i : failed";
       nok=`expr $nok + 1`
   fi;

   i=`expr $i + 1`

done

echo "checked well formed messages:   $i"
echo "errors                      :   $nok"

ok=0
nok=0

i=0
while [ $i -lt 9 ]
do
set +x
#  mpatrol -C -S -L -j -d --list -p -t --use-debug ./test/torture_test $1 $i $2 $3
   ./torture_test ./res/sip-malformed$i 0 $1
   if [ "$?" -eq 0 ]; then
       echo "checking sip$i : passed";
       ok=`expr $ok + 1`;
   else
       echo "checking sip$i : failed";
       nok=`expr $nok + 1`
   fi;

   i=`expr $i + 1`

done

echo "checked malformed messages:   $i"
echo "errors                    :   $ok"



